feat: clean application and creat a splash and home page
Lifeados/desafio-globo pull request #1
Opened 2024-09-17 17:08 UTC by IngridMetzker

Realizado a limpeza do projeto excluindo a pasta Test, limpando o arquivo pubspec.yaml. 

Adicionado a pasta .vsco + o arquivo lunch.json para a execução do codigo.

Criado a pagina de splash e também a pagina Home.

2024-09-19 01:04 UTC, LucasSakuma requested changes

2024-09-19 01:04 UTC, LucasSakuma commented on pubspec.yaml
> -  # see https://flutter.dev/custom-fonts/#from-packages
Achei o erro pelo qual ontem não estava carregando a imagem, a propriedade `assets:` pertence ao `flutter: ` o erro esta ocorrendo devido a identaçao.

2024-09-19 01:07 UTC, LucasSakuma requested changes

2024-09-19 01:07 UTC, LucasSakuma commented on pubspec.yaml
> +assets:
@IngridMetzker o erro esta na indentação do seu código, a propriedade `assets:` pertence ao `flutter:`

2024-09-23 01:03 UTC, HiroGarcia approved these changes

2024-09-24 03:29 UTC, LucasSakuma approved these changes

2024-09-24 21:11 UTC, dionedev approved these changes

2024-09-24 22:28 UTC, merged